name: tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - scikit-learn
      - mlflow
      - pandas
      - tensorflow-macos==2.11.0
      - cloudpickle==2.2.1
      - seaborn
      - gensim
      